### ISSUE TITLE
  The "meta" tag is a valid HTML element but is not handled by this library. You must extend the default HTMLElementModel for this tag with "customHTMLElementModels" prop and make sure its content model is not set to "none". If you don't want this tag to be rendered, add it to "ignoredDomTags" prop array. 

### ISSUE THREAD

**Issue by VivekTechP** [meliorence/react-native-render-html#594]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

  The "meta" tag is a valid HTML element but is not handled by this library. You must extend the default HTMLElementModel for this tag with "customHTMLElementModels" prop and make sure its content model is not set to "none". If you don't want this tag to be rendered, add it to "ignoredDomTags" prop array. 

### React Native Information

```sh
System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4670T CPU @ 2.30GHz
    Memory: 151.13 MB / 11.64 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.22.12 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.16 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

### RNRH Version

"react-native-render-html": "^6.3.4",

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

w

**Comment by jsamr** [comment]
Closing because no minimal reproducible example was provided. Feel free to reopen with a reproduction.
